### ISSUE TITLE
Effect not showing behind hat

### ISSUE THREAD

**Issue by dragontwist** [juliarose/steam-trade-offer-enhancer#4]
I own a Frostbite nunhood, and it doesnt show the effect like other hats

![image](https://github.com/juliarose/steam-trade-offer-enhancer/assets/21246746/0e147d13-8749-4c9f-aee4-1f4cad9cde53)

**Comment by juliarose** [comment]
I don't see anything that would trigger this issue. You seem to be using another extension which may have an effect on things. Try inspecting the element and see if it's applying a background image to the item. Effects will have a URL to backpack.tf where the particle images are sourced. Particularly for Frostbite this should be <https://backpack.tf/images/440/particles/87_94x94.png>.

**Comment by dragontwist** [comment]
> I don't see anything that would trigger this issue. You seem to be using another extension which may have an effect on things. Try inspecting the element and see if it's applying a background image to the item. Effects will have a URL to backpack.tf where the particle images are sourced. Particularly for Frostbite this should be https://backpack.tf/images/440/particles/87_94x94.png.

I have checked other Frostbite hats which work, so im assuming its due to the hat size covering the effect, which i didnt think of when i posted the issue.

![image](https://github.com/juliarose/steam-trade-offer-enhancer/assets/21246746/c91a89e1-0272-4422-b155-89b64c8da6f7)

and looking at Bp.tf it seems to be the same issue, so it has to just be due to the size of the PNG of that hat.

![image](https://github.com/juliarose/steam-trade-offer-enhancer/assets/21246746/053f4c9d-4744-411e-9557-e2e0337167aa)

Which in hindsight i didnt think off, Sorry.
